title: Rudd Fawcett
email: rudd.fawcett@gmail.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "/" # the subpath of your site, e.g. /blog
url: "rudd.fyi" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ruddfawcett
github_username:  ruddfawcett

permalinks: pretty

sass:
  style: compressed

collections_dir: work
collections:
  yale:
    output: true
    permalink: /:collection/:name
  rca:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "yale"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "rca"
    values:
      layout: "work"
